PrinsFrank/standards

- composer.json
- dev/SpecUpdater.php
- update-spec
@PrinsFrank What are you thoughts?
1 less file! ⬇️
> Run SpecUpdater in a Composer way

- .github/workflows/codestyle.yml
🤯 https://getcomposer.org/doc/03-cli.md#check-platform-reqs
`check` is an actual Composer command!!
> Fix Composer script in CI

- README.md
👀 https://youtu.be/Skq62zB750Y?t=3
> #helloTürkiye :) Go 100% Turkish

- src/Country/ISO3166_1_Alpha_2.php
- src/Country/ISO3166_1_Alpha_3.php
- src/Country/ISO3166_1_Numeric.php
Reverts PrinsFrank/standards#15
> Revert "Automatic spec update"

- src/BackedEnum.php
> Simplify BackedEnum

- UPGRADING.md
- src/CountryCallingCode/CountryCallingCode.php
> Fix typo in Global Mobile Satelite System

- .gitattributes
Lighten the load on everybody.
> Do not distribute PNG images

- .github/workflows/phpstan.yml
- .gitignore
- phpstan.neon
6 minutes 👉🏻 1 second
https://github.com/phpstan/phpstan/discussions/9301
https://github.com/PrinsFrank/standards/actions/caches 📦
> Speed up PHPStan execution

- composer.json
> Synchronize PHPStan usage

- UPGRADING.md
- src/Country/CountryAlpha2.php
- src/Country/CountryAlpha3.php
- src/Country/CountryName.php
- src/Country/CountryNumeric.php
- src/Language/LanguageAlpha2.php
- src/Language/LanguageAlpha3Bibliographic.php
- src/Language/LanguageAlpha3Extensive.php
- src/Language/LanguageAlpha3Terminology.php
- tests/Unit/Country/CountryAlpha2Test.php
- tests/Unit/Country/CountryAlpha3Test.php
- tests/Unit/Country/CountryNameTest.php
- tests/Unit/Country/CountryNumericTest.php
- tests/Unit/Language/LanguageAlpha2Test.php
- tests/Unit/Language/LanguageAlpha3BibliographicTest.php
- tests/Unit/Language/LanguageAlpha3ExtensiveTest.php
- tests/Unit/Language/LanguageAlpha3TerminologyTest.php
> Add methods for country names in language

- .github/workflows/codestyle.yml
❌ Should fail!
[_source_](https://github.com/szepeviktor/byte-level-care/blob/780a49deff6c7b0abfe30800f009ca060de6ef8d/.github/workflows/back-end.yml#L161-L163)
> Check PSR-4 mapping

- src/Language/LanguageAlpha3Extensive.php
- src/Scripts/ScriptAlias.php
- src/Scripts/ScriptCode.php
- src/Scripts/ScriptName.php
- src/Scripts/ScriptNumber.php
> Fix non-alphanumeric keys

- .gitattributes
- .github/workflows/ci.yml
- .typos.toml
- README.md
- UPGRADING.md
Prevent future fat fingers and ESL mistakes.
From #140
> Add typos CI job

- .github/workflows/reusable-update-spec.yml
- .github/workflows/update-spec-country.yml
- .github/workflows/update-spec-currency.yml
- .github/workflows/update-spec-http-methods.yml
- .github/workflows/update-spec-http-status-codes.yml
- .github/workflows/update-spec-language-extensive.yml
- .github/workflows/update-spec-language-sub-tag.yml
- .github/workflows/update-spec-language.yml
- .github/workflows/update-spec-scripts.yml
name: "Shared"
file name: "reusable-"
[_source_](https://github.com/szepeviktor/byte-level-care/tree/master/.github/workflows)
> Mark shared workflow

- .github/workflows/reusable-update-spec.yml
> Upgrade peter-evans/create-pull-request action

- dev/DataTarget/NameNormalizer.php
From https://github.com/PrinsFrank/standards/pull/171#discussion_r1468947616
> Throw exception for empty key in NameNormalizer

- .github/workflows/ci.yml
👉🏻 https://www.deepl.com/write
> Improve English in CI comment

- dev/DataTarget/NameNormalizer.php
- src/TopLevelDomain/CountryCodeTLD.php
That is not written with Sinhala but with Lao.
> Fix Lao script name in NameNormalizer

- dev/DataTarget/EnumFile.php
💥 Allow duplicated keys.
For #182
> Danger is my middle name!

- .github/workflows/ci.yml
No more ![image](https://github.com/PrinsFrank/standards/assets/952007/d1ae13ea-f377-48ee-9d83-826755164c33)
> Do not fail phpstan caching

- .php-cs-fixer.php
- dev/DataTarget/EnumMethod.php
> Enforce concat_space in CS

- .github/workflows/reusable-update-spec.yml
This is a big difference between the two workflows.
Maybe the cause of #220
> Set up PHP in reusable-update-spec

- dev/DataSource/Mapping/CountryMapping.php
> Click cookie button in CountryMapping

- .typos.toml
@PrinsFrank Goes into your PR.
> Ignore language names in "Name" attributes

- src/Currency/CurrencyAlpha3.php
> fix url in CurrencyAlpha3

- dev/DataSource/Mapping/CurrencyMapping.php
Make country names readable.
GitHub even glitches out from the long line.
Try scrolling horizontally!
> Improve CurrencyMapping

- dev/DataSource/Mapping/HttpStatusCodeMapping.php
- dev/DataTarget/EnumCaseAttribute.php
- src/Http/Attributes/TemporaryAssignment.php
- tests/Unit/Http/Attributes/TemporaryAssignmentTest.php
Needed for #273 to indicate temporary assignment
> Add support for temporary assignments attributes in HTTP status codes

- src/TopLevelDomain/ReservedTLD.php
> Add ReservedTLD

- src/TopLevelDomain/AnyTLD.php
> Add AnyTLD

- .github/workflows/specs-regeneration.yml
- .github/workflows/update-spec-uri-scheme.yml
- composer.json
- dev/DataSource/Mapping/URISchemeMapping.php
- src/URIScheme/Attributes/Status.php
- src/URIScheme/URIScheme.php
- src/URIScheme/URISchemeStatus.php
- tests/Unit/URIScheme/Attributes/StatusTest.php
- tests/Unit/URIScheme/URISchemeTest.php
> Add URI Schemes

- README.md
- src/Currency/CurrencyAlpha3.php
- src/Currency/CurrencyName.php
- src/Currency/CurrencyNumeric.php
- src/Currency/MinorUnits/CurrencyMinorLowerLastAlpha3.php
- src/Currency/MinorUnits/CurrencyMinorUpperXAlpha3.php
- tests/Unit/Currency/CurrencyAlpha3Test.php
- tests/Unit/Currency/CurrencyNameTest.php
- tests/Unit/Currency/CurrencyNumericTest.php
- tests/Unit/Currency/MinorUnits/CurrencyMinorLowerLastAlpha3Test.php
- tests/Unit/Currency/MinorUnits/CurrencyMinorUpperXAlpha3Test.php
> Implement currency minor units

- dev/DataSource/Mapping/LanguageExtensiveMapping.php
https://iso639-3.sil.org/code_tables/download_tables
> Fix source for LanguageExtensiveMapping

- dev/DataSource/Mapping/CountryMapping.php
- src/Country/CountryName.php
> Update bahamas country name ("the" became "The")
